framework:
    default_locale: pt_BR
    # default_locale: en
    enabled_locales: ['en', 'pt_BR']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
